### ISSUE TITLE
twitter feed

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#10]
Is it possible to add the scikit-learn twitter feed to a Jekyll blog?

**Comment by laurburke** [comment]
I'm looking into it!

**Comment by laurburke** [comment]
Where would we want this embedded, location-wise? Under the sidebar menu? At the bottom of the page?

@reshamas

**Comment by laurburke** [comment]
@reshamas Embedded as a sticked sidebar on the right! https://scikit-learn.org/blog/

**Comment by reshamas** [comment]
@laurburke It looks beautiful!  Thank you!!!

**Comment by laurburke** [comment]
@reshamas Most other blogs I've looked at only have the feed on the home page, so I did the same. 

Can you think of any other pages that would benefit from the blog? Maybe the calendar?

**Comment by reshamas** [comment]
@laurburke I think the twitter feed looks ok on the home page of the blog.
