### ISSUE TITLE
HTTPS certificate for the blog has expired

### ISSUE THREAD

**Issue by lesteve** [scikit-learn/blog#108]
Going to https://blog.scikit-learn.org/ gives a certificate warning, not sure who created the HTTPS certificate originally (looks like it was created with Let's Encrypt). 

![image](https://user-images.githubusercontent.com/1680079/165549102-44a6832c-db23-41c4-afaf-78f76c7bfbd0.png)

Looks like the certificate was created with a validity of 3 months and has recently expired:

![image](https://user-images.githubusercontent.com/1680079/165549402-01298ca8-fcb4-43e0-b263-fdb4ab8701ce.png)

Note as a work-around that http://blog.scikit-learn.org/ does work.

**Comment by ogrisel** [comment]
I had a look at: https://github.com/scikit-learn/blog/settings/pages and I found:


![Screenshot from 2022-04-28 10-25-48](https://user-images.githubusercontent.com/89061/165710590-8b1da960-48c4-4d86-a393-c770d4e3feeb.png)


This looks like the problem described here:

https://github.community/t/certificate-request-error-is-persistent-tls-certificate-cant-be-provisioned/11008

I have changed the DNS config to turn the entry for `www` into a `CNAME` entry pointing to `scikit-learn.org.`:


```
$ dig www.scikit-learn.org
[...]
;; ANSWER SECTION:
www.scikit-learn.org.	55	IN	CNAME	scikit-learn.github.io.
scikit-learn.github.io.	952	IN	A	185.199.110.153
scikit-learn.github.io.	952	IN	A	185.199.108.153
scikit-learn.github.io.	952	IN	A	185.199.111.153
scikit-learn.github.io.	952	IN	A	185.199.109.153
```

Previously, `www` was an `A` entry pointing to gandi.net web redirection service.


Let's wait a bit to see if it fixes the problem.

**Comment by lesteve** [comment]
Seems to work for me now, thanks for the fix!

**Comment by ogrisel** [comment]
I also changed the CNAME of `blog` to point to `scikit-learn.github.io.` instead of `scikit-learn.org.`:

```
$ dig blog.scikit-learn.org
[...]
;; ANSWER SECTION:
blog.scikit-learn.org.	3577	IN	CNAME	scikit-learn.github.io.
scikit-learn.github.io.	3595	IN	A	185.199.110.153
scikit-learn.github.io.	3595	IN	A	185.199.109.153
scikit-learn.github.io.	3595	IN	A	185.199.108.153
scikit-learn.github.io.	3595	IN	A	185.199.111.153
```
