### ISSUE TITLE
MathJax Javascript: for rendering formulas

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#126]
To use MathJax we need to include the Javascript that does all the work ([MathJax documentation](http://docs.mathjax.org/en/latest/web/start.html#using-mathjax-from-a-content-delivery-network-cdn)).

If we want to include the script in every page of the blog (note that it may slow down pages without LaTeX, I don't know how much though), we can edit the file `blog/_includes/head/custom.html` adding:
```html
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
```
This will load an specific version of MathJax. There are other urls we can use to load the latest version but we'll need to check the documentation.
Also, MathJax can be configured in different ways, but I think with the defaults we'll be OK.

_Originally posted by @jmloyola in https://github.com/scikit-learn/blog/issues/70#issuecomment-1131717624_

---
https://github.com/scikit-learn/blog/pull/70#issuecomment-1132930094

>Looking at the PR (should have done that earlier) everything looks OK here.
The script for MathJax is loaded only when needed (using page.usemathjax).
Maybe the math formulas were not rendering because of the URL to the MathJax script.
Or maybe the place where the URL was inserted was not correct (_includes/masthead.html).
I'm not sure. We'll need to debug this to find out.

>I know you already solved this, but if you start seeing loading delays in pages without math it might be related to always loading the MathJax script.
In that case, we have to do something similar to what this PR did.

**Comment by reshamas** [comment]
@jmloyola 
I opened a new issue to keep track.
It does seem it has slowed down the blog, just a bit, but still it is noticeable.

**Comment by reshamas** [comment]
Comparatively, my Data Umbrella blog is loading faster:
https://blog.dataumbrella.org

**Comment by jmloyola** [comment]
I looked into the [network monitor in Firefox](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_details/#network-monitor-request-details-timings-tab), and it doesn't seem to be MathJax responsible for the loading times.

Most of the time is taken (in my case) by the images.

![image](https://user-images.githubusercontent.com/2133361/174126763-f8896839-0efe-41b6-8394-f78b6e084851.png)

@reshamas, can you try the same to confirm this?
When you do, remember to disable the cache. Thus, the times resemble those of a person that first loads the page.

To improve the times, we can reduce the size of the images

**Comment by reshamas** [comment]
@jmloyola 
Do I need to build Firefox on my local computer?  
My computer is a bit too old to add any more builds, at the moment.

**Comment by jmloyola** [comment]
No, you don't need to build Firefox.
In most browsers (I think), if you press the F12 key, a developer console will pop out.
It will present you with a lot of information about the current page you are looking at.
Once that is open, reload the page and go to the "Network" tab.
There you'll see the amount of time each page component took.

**Comment by reshamas** [comment]
@jmloyola 
Will you be at June 27 office hours? We could discuss more then. 
I doubt I will make it to Jun 17 Triage Team mtg.

**Comment by jmloyola** [comment]
Yes, I'll try to join the office hours.

**Comment by reshamas** [comment]
Note:  with every new image, we should check the size.
Chrome:  F12, F5 (disable cache) and then look at image time loading

**Comment by reshamas** [comment]
Note:  resize gdbt.png
