### ISSUE TITLE
Set up Google Analytics tracking code

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#13]
@GaelVaroquaux 

This item is a bit urgent. Who's the best person to assist with creating a code?

cc:  @laurburke

**Comment by GaelVaroquaux** [comment]
I wonder if we can reuse the same tracking as with the main scikit-learn website. On the main scikit-learn website, the code that does the tracking is the following:
```
<script>
    window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
    ga('create', 'UA-22606712-2', 'auto');
    ga('set', 'anonymizeIp', true);
    ga('send', 'pageview');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

```

**Comment by laurburke** [comment]
If we want to track the blog traffic separately, we should create and use a different universal analytics property (UA-). I would recommend using this so we can see how people are interacting with the blog. I can set this up. 

@reshamas @GaelVaroquaux

**Comment by GaelVaroquaux** [comment]
> If we want to track the blog traffic separately, we should create and use a different universal analytics property (UA-).

Fine with me.

Thanks!

**Comment by laurburke** [comment]
Google Analytics has been setup and is confirmed connected and working.
