### ISSUE TITLE
Joining forces with Hugging Face

### ISSUE THREAD

**Issue by francoisgoupil** [scikit-learn/blog#141]
Given what Hugging Face can bring to the scikit-learn users through skops for instance:
    - The ability to push scikit-learn models on the Hugging Face Hub
    - The possibility to try out models directly in the browser
    - The automatic creation of model cards, to improve model documentation and understanding
    - The ability to collaborate with others on machine learning projects

Given their open source DNA and what they do for the library like hiring core devs and contributors, sponsoring the INRIA consortium and more, I suggest we either publish or cross post this blog post: 
https://scikit-learn.fondation-inria.fr/scikit-learn-and-hugging-face-join-forces/

I will be happy to read you and make a PR

**Comment by reshamas** [comment]
https://blog.scikit-learn.org/updates/community/joining-forces-hugging-face/
