### ISSUE TITLE
blog post: interview with MZ

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#146]
Instructions for posting the interview:  
- copy one of the previous ones, such as:  https://github.com/scikit-learn/blog/blob/main/_posts/2022-05-22-norbert-interview.md
- For authors, let's put "Reshama Shaikh, Meekail Zain"
- In top line, can include "Posted by xxx"
- I have highlighted some text in blue, which we do want highlighted in the blog.  
Here is an example of code to highlight:  
```
>*<span style="background-color: #CAE9F5;">
What is the effectiveness of sprint models and what is the long-term engagement as a result of these sprints?
</span>*
```

Reminders:  
- let's check that the words in italics get copied over
- we'll need to create a social media card

Unfortunately, we don't have Netlify set up for this, so we may need to make updates after the blog PR is accepted.

link to interview doc:  Reshama will email

**Comment by reshamas** [comment]
@Micky774 Would you like to include a photo to share on social media?
We can take this one:
https://www.linkedin.com/in/meekail-zain-02a412a2/

cc:  @SangamSwadiK

**Comment by Micky774** [comment]
Sure! Here's the source image for reference: 
<details>
<summary> Image </summary>

![image](https://user-images.githubusercontent.com/34613774/204567597-7371a4c7-b175-411c-a452-ed5e59873120.jpg)

</details>

**Comment by reshamas** [comment]
@SangamSwadiK Can we update Q2 response?

2. How did you first get involved in open source?
I first got involved as a user, as most people do. NumPy was a recurring day-to-day library for me, and scikit-learn was a de-facto necessity for several graduate courses. Originally I never really imagined being able to get to a point where I could affect change in these libraries since they seemed so well-established!

**Comment by reshamas** [comment]
@SangamSwadiK 
There are a few words with the italics missing.  Let me know if you can double check the raw interview and make those updates.  I highlighted them in yellow in the document, so they are more easily visible, hopefully that helps?

**Comment by reshamas** [comment]
@SangamSwadiK 
Based on the raw doc file, Meekhail intended for the last sentence here to be its own line, rather than a bullet point. 

```text
- Aside from expertise, are there other socio-economic or general demographics that exhibit consistent bottlenecks? (e.g. access to hardware)
- How do we create informed and effective DEI policies from this information?

OSS projects thrive and prosper based on their community, so I would love to see more systematic research on community needs and pain points.
```

Can we make that fix?

@Micky774 
Would you have any other edits for this post?
