### ISSUE TITLE
blog image not rendering

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#15]
@laurburke 
When I preview my post in VSCode, I can see the header image.

But, as you see here, it's not rendering.  Any idea why?

<img width="547" alt="Screen Shot 2022-01-10 at 9 09 58 AM" src="https://user-images.githubusercontent.com/2507232/148779556-83f06402-ef97-49fa-b2dd-765825c80727.png">

**Comment by laurburke** [comment]
@reshamas This is weird...it works locally for me as well.

**Comment by laurburke** [comment]
Fixed it! Images will need to have URLs "/blog/assets/images/..."

**Comment by reshamas** [comment]
Thanks @laurburke !
(I recall Jekyll has its peculiarities.)
