### ISSUE TITLE
sprints: add in PyLadies Berlin events

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#158]
Page:  
https://blog.scikit-learn.org/sprints/

Add events:  
-  2023-02-23: https://www.meetup.com/en-AU/pyladies-berlin/events/291249163/
-  2023-02-15: https://www.meetup.com/en-AU/pyladies-berlin/events/291248660/

cc:  @marenwestermann

**Comment by marenwestermann** [comment]
Thank you, Reshama! I'll submit a PR for it later today.
