### ISSUE TITLE
Announce 2024 user survey

### ISSUE THREAD

**Issue by InessaPawson** [scikit-learn/blog#186]
We are getting very close to the launch of the 2024 user survey and would like to start a discussion on placing an announcement on the blog.
Find below 3 options that are proposed by the POSSEE team working on this project (@otieno-juma, @ethanlanders, @inessapawson).

**Option 1:** A callout bar on the [blog homepage](https://scikit-learn.org/stable/). The wording in the announcement is to be refined.

![sklearnsurvey-announcement1](https://github.com/user-attachments/assets/657be545-09d4-4d91-8da8-fca8e15d4ed2)

**Option 2:** A callout box on the [Getting Started page](https://scikit-learn.org/stable/getting_started.html). The wording in the announcement is to be refined.

![sklearnsurvey-announcement2](https://github.com/user-attachments/assets/ec593881-33c9-425a-8342-5dee9567f7be)

**Option 3:** A callout box on the [User Guide homepage](https://scikit-learn.org/stable/user_guide.html). The placement would be similar to Option 2.

**Comment by ccosborne** [comment]
I vote for option 1

**Comment by betatim** [comment]
When I visit the links to the announcements I see nothing, just an empty page :-/

**Comment by betatim** [comment]
Seems like it has fixed itself, I now see images in the first comment in this issue. Before they were just links.

Do we have to pick one of the options? As in, why not everywhere?

**Comment by InessaPawson** [comment]
> ... why not everywhere?

@betatim This could be Option 4.:))

**Comment by GaelVaroquaux** [comment]
>     ... why not everywhere?

I would vote for that.

Thanks for pushing this forward!

**Comment by InessaPawson** [comment]
@GaelVaroquaux @betatim Thank you for your feedback! We will plan on implementing Options 1-3.

**Comment by InessaPawson** [comment]
After further discussions on the technical implementation of this task with several scikit-learn core team members, I've used the `announcement` key from `pydata-sphinx-theme` which adds the announcement to all the pages of the scikit-learn documentation. For details, refer to https://github.com/scikit-learn/scikit-learn/pull/29732
