### ISSUE TITLE
change name of blog repo

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#2]
Is it possible to rename the repo from the current "blog"?  Some options:  
- scikit-learn-blog
- sklearn-blog

The reason:  
When I clone the repo, the name is "blog" and it's not that informative, especially in a local folder with multiple blog repo's. What do you think? I don't know if there is a naming convention for blog repo code.

We had discussed setting up a CNAME that the address would be:  blog.scikit-learn.org

cc:  @laurburke @GaelVaroquaux @thomasjpfan @jjerphan @ogrisel

**Comment by adrinjalali** [comment]
I think I would rather keep the name. Locally, I tend to have all the clones of a project under the same folder, so for me it'd be `/path/to/sklearn-stuff/blog`. It would also be redundant in our org's list of repos if it's like `github.com/scikit-learn/scikit-learn-blog`, whereas I kinda like `github/scikit-learn/blog`.

Note that you can rename your fork of the repo and make it scikit-learn-repo, and reflect that on your local clone, and you won't need to change the name of the original/upstream to do that AFAIK.

**Comment by GaelVaroquaux** [comment]
I believe that the name of the repo conditions the url under which it will be accessible: http://scikit-learn.org/blog

We can probably do some work at the DNS level to expose any url as http://blog.scikit-learn.org , in which case we can rename the repo to whatever we want. This requires a bit of work from DNS admins ( at least @ogrisel and myself, but probably others).

**Comment by thomasjpfan** [comment]
In the meantime, you can use a different folder name for your local copy:

```bash
git clone https://github.com/reshamas/blog sklearn-blog
```

**Comment by reshamas** [comment]
Ok, so now that the blog is in production, I am little less inclined to change the name of the repo.  However, I still think it would have been better practice to name it "scikit-learn-blog" instead of "blog".  Unfortunately, I didn't catch it earlier.

I agree it's a good practice to create a folder with project repos.  However, that is not a best practice I was familiar with.  Imagine new folks working with git, github, blogs, repos, etc. If the blog repo had an informative name, it would help them as well. 

@adrinjalali Adding this to my list of best practices that developers should do, but are not formally taught:  
- create a separate virtual environment for each of your projects
- create a separate directory by projects for repos that you clone

I'll write a personal blog on it, one day.
