### ISSUE TITLE
Calendar Time Zone

### ISSUE THREAD

**Issue by cmarmo** [scikit-learn/blog#21]
Hello! Thanks for setting up the blog!
Could it be possible to have the calendar in Universal Time?
I personally find easier to remember my difference time with UTC, than with some other specific time zone.

Thanks!

**Comment by reshamas** [comment]
to do:  update iframe code

```
<iframe src="https://calendar.google.com/calendar/embed?src=social.scikitlearn%40gmail.com&ctz=Antarctica%2FTroll" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

**Comment by reshamas** [comment]
Thanks @cmarmo.
