### ISSUE TITLE
add bot: welcome to first issue / PR

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#22]

**Comment by reshamas** [comment]
link to Contributing guide needs to be updated in this yaml file since it was renamed:
https://github.com/scikit-learn/blog/blob/main/.github/config.yml

**Comment by laurburke** [comment]
@reshamas Changed it back!

**Comment by reshamas** [comment]
Welcome Bot has finally been installed.  This issue can be closed.

https://github.com/behaviorbot/welcome?setup_action=request#usage
