### ISSUE TITLE
Chiara interview: numbering of questions

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#39]
@laurburke @jmloyola 

Any idea why the numbering isn't working with the questions?
Should I hardcode the numbers in?
https://scikit-learn.org/blog/team/chiara-interview/

**Comment by jmloyola** [comment]
I think you need to indent each of the paragraphs inside the answers. Otherwise, the other numbers are considered a new numbered list.
Like this:
```
1. __Tell us about yourself.__

	I’m Chiara, I’m Italian, from Biella, a small town in the North of Piedmont. I have a PhD in Astronomy. I am a Research Engineer and a French civil servant. I have worked in data processing and archiving for Astronomy, Earth and Planetary Sciences. Right now, I’m living in the US with my family.
```

**Comment by laurburke** [comment]
@reshamas, @jmloyola is correct. For a non-numbered paragraph, you need to indent it 4 spaces. Otherwise it will drop the number sequence.

**Comment by reshamas** [comment]
Thank you @jmloyola @laurburke.  It's fixed now.
