### ISSUE TITLE
embed public calendar

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#4]
@laurburke 
RE:  events

Can we embed our public calendar on the separate page for "Events"?

```
<iframe src="https://calendar.google.com/calendar/embed?src=social.scikitlearn%40gmail.com&ctz=America%2FNew_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

**Comment by laurburke** [comment]
Done! https://scikit-learn.org/blog/calendar

**Comment by laurburke** [comment]
@reshamas Should I add a snippet above or below with instructions on how to add the calendar to a personal calendar?
