### ISSUE TITLE
write post summarizing Thomas's video on PR etiquette

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#43]
I can do this. Unless you would like to do it, @thomasjpfan.

### Reference
https://youtu.be/dyxS9KKCNzA

**Comment by francoisgoupil** [comment]
I can also do this if you want

**Comment by reshamas** [comment]
@francoisgoupil 
Sure, that works. I put the link to Thomas's slides and other key information in the video description. 
We can also embed the video in the blog, so folks have it for reference.

Example:  
https://blog.dataumbrella.org/pair-programming-with-visual-studio-code-live-share
