### ISSUE TITLE
add instructions on how to run blog locally

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#5]
Can we add instructions on how to run the blog locally, in the blog repo.

As an example, I have this for Data Umbrella, that came with the template.  Not that I have been unable to get my own blog running locally.
https://github.com/data-umbrella/data-umbrella.github.io#installation

Some instructions on what needs to be installed and getting it running will be helpful for folks.

**Comment by laurburke** [comment]
Done!
